sudo: false

language: haskell

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/importify/.stack-work"

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # Update needed Trusty package
  ## Update info explicitly
  - sudo apt-get -qq update
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
  # Install GHC for current project
  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version

  # Build project dependencies
  - travis_wait 30 stack build --only-dependencies --no-terminal

  # Build project itself
  - travis_wait 30 stack build --test --bench --no-run-tests --no-run-benchmarks --no-terminal

script:
  - travis_wait 30 stack test --no-terminal && find / -name HsBaseConfig.h 2> /dev/null

notifications:
  email: false
  slack:
    rooms:
      - serokell:JWBvWb5PKOhknocQgcoQnflZ
    on_success: change
    on_failure: always
