resolver: lts-9.6

packages: ['.']

extra-deps:
- fmt-0.5.0.0
- haskell-names-0.9.0
- log-warper-1.3.2
- path-0.6.1
- path-io-1.3.3
- universum-0.7.0

flags: {}
extra-package-dbs: []

nix:
    packages: [stack, binutils]

